# write a program to accept marks of 6 students and display them in a stored manner
marks=[]
F1=input("enter the 1st marks")
marks.append(F1)
F2=input("enter the 2nd marks")
marks.append(F2)
F3=input("enter the 3rd marks")
marks.append(F3)
F4=input("enter the 4th marks")
marks.append(F4)
F5=input("enter the 5th marks")
marks.append(F5)
F6=input("enter the 6th marks")
marks.append(F6)
F7=input("enter tmarks marks")
marks.append(F7)
print(marks)